# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("discount.proto", :syntax => :proto3) do
    add_message "discount.GetDiscountRequest" do
      optional :productID, :int32, 1
    end
    add_message "discount.GetDiscountResponse" do
      optional :percentage, :float, 1
    end
  end
end

module Discount
  GetDiscountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.GetDiscountRequest").msgclass
  GetDiscountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.GetDiscountResponse").msgclass
end
