# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discount.proto for package 'discount'

require 'grpc'
require_relative 'discount_pb'

module Discount
  module Discount
    # Service that return mocked discount percentage.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'discount.Discount'

      rpc :GetDiscount, ::Discount::GetDiscountRequest, ::Discount::GetDiscountResponse
    end

    Stub = Service.rpc_stub_class
  end
end
